name: rbp_analysis_interactive_tool
channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - python
  - pip
  - bokeh==3.5.0
  - markov-clustering
  - networkx==3.2.1
  - pandas
  - openjdk==20.0.0
  - scipy
  - mypy
  - openpyxl
  - matplotlib
  - tqdm
